name: build

on:
  push

permissions:
  contents: read
  checks: write
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        php: ['php5', 'php7']
        include:
          - php: 'php5'
            php_version: '5.6'
          - php: 'php7'
            php_version: '7.0'

    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: install dependencies
      run: composer install

    - name: lint
      run: composer syntax
  
    - name: tests
      run: composer test -- -C
  